# driverClassName=oracle.jdbc.OracleDriver
# url=jdbc:oracle:thin:@192.168.35.98:1521/xe
driverClassName=com.p6spy.engine.spy.P6SpyDriver

## local###
# url=jdbc:p6spy:oracle:thin:@192.168.35.95:1521/xe
# username=KHC95
# password=java

## cloud###
url=jdbc:p6spy:oracle:thin:@khc95_high?TNS_ADMIN=/home/ho/Oracle_Cloude_Database/KHC95/Wallet_KHC95
username=admin
password=Tmddusdk4fkdgo!

maxPoolSize=5
minIdle=3
connectionTimeoutMs=20000