
--P101000001 상품의 기본 정보와 해당 상품의 제조사명, 제조사 담당자명을 조회하세요
SELECT P.*, B.BUYER_NAME, B.BUYER_CHARGER
FROM PROD P INNER JOIN BUYER B ON (P.BUYER_ID = B.BUYER_ID)
WHERE P.PROD_ID = 'P101000001';

SELECT PROD_NAME, PROD_ID, BUYER_ID, BUYER_NAME, BUYER_CHARGER
FROM PROD NATURAL JOIN BUYER
WHERE PROD_ID = 'P101000001';

-- P10101 제조사의 기본 정보와 해당 제조사와의 거래 품목(품목코드, 품목명) 조회
SELECT B.*, PROD_ID, PROD_NAME
FROM BUYER B RIGHT OUTER JOIN PROD P ON (P.BUYER_ID = B.BUYER_ID)
WHERE B.BUYER_ID = 'P10101';

-- 거래 품목이 없는 제조사만 조회. 제조사 조회, 거래품목이 없는 제조사를 조건으로
SELECT *
FROM BUYER
WHERE BUYER_ID NOT IN (SELECT BUYER_ID FROM PROD);

-- 회원들 중에서 상품을 한번이상 구매(CART)한 적이 있는 회원의 기본 정보 조회(MEMBER)
SELECT * 
FROM MEMBER
WHERE MEM_ID IN (SELECT MEM_ID FROM CART);

-- 회원들 중에서 상품을 한번이상 구매(CART)한 적이 있는 회원의 기본 정보(MEMBER)와 구매 상품 코드(CART) 조회
SELECT MEM_ID, MEM_NAME, PROD_ID
FROM MEMBER NATURAL JOIN CART;

-- 회원의 기본 정보(MEMBER)와 구매 상품 코드(CART) 조회
SELECT *
FROM MEMBER M LEFT OUTER JOIN CART C ON (M.MEM_ID = C.MEM_ID)
WHERE M.MEM_ID = 'n001';

--P101000001 상품 코드, 상품명(PROD), 분류 코드, 분류명(LPROD)와 해당 상품의 제조사명, 제조사 담당자명(BUYER)을 조회하세요
SELECT P.PROD_ID, P.PROD_NAME, P.LPROD_GU, LPROD_NAME, BUYER_NAME, B.BUYER_CHARGER
FROM PROD P INNER JOIN LPROD L ON (P.LPROD_GU = L.LPROD_GU)
            INNER JOIN BUYER B ON (P.BUYER_ID = B.BUYER_ID)
WHERE PROD_ID = 'P101000001';

-- P10101 제조사의 기본 정보와 해당 제조사와의 거래 품목(품목코드, 품목명, 상품분류명) 조회
SELECT B.*, PROD_ID, PROD_NAME, P.LPROD_GU
, LPROD_NAME
FROM BUYER B LEFT OUTER JOIN PROD P ON (P.BUYER_ID = B.BUYER_ID)
             LEFT OUTER JOIN LPROD L ON (P.LPROD_GU = L.LPROD_GU)
WHERE B.BUYER_ID = 'P10103';

SELECT B.*, PROD_ID, PROD_NAME, P2.LPROD_GU
, LPROD_NAME
FROM BUYER B LEFT OUTER JOIN (
        SELECT *
        FROM
        PROD P INNER JOIN LPROD L ON (P.LPROD_GU = L.LPROD_GU)
        ) P2 ON (P.BUYER_ID = B.BUYER_ID)
WHERE B.BUYER_ID = 'P10103';


WITH A AS (
    SELECT *
    FROM
        PROD P INNER JOIN LPROD L ON (P.LPROD_GU = L.LPROD_GU)
)
SELECT *
FROM BUYER B LEFT OUTER JOIN A ON (B.BUYER_ID = A.BUYER_ID)
WHERE B.BUYER_ID = 'P10103';


-- 상품 기본정보와 분류정보 제조사 정보를 모두 조회
CREATE OR REPLACE VIEW PRODVIEW AS 

SELECT
PROD_ID,
PROD_NAME,
P.LPROD_GU,
P.BUYER_ID,
PROD_COST,
PROD_PRICE,
PROD_SALE,
PROD_OUTLINE,
PROD_DETAIL,
PROD_IMG,
PROD_TOTALSTOCK,
PROD_INSDATE,
PROD_PROPERSTOCK,
PROD_SIZE,
PROD_COLOR,
PROD_DELIVERY,
PROD_UNIT,
PROD_QTYIN,
PROD_QTYSALE,
PROD_MILEAGE,
LPROD_NAME,
BUYER_NAME,
BUYER_BANK,
BUYER_BANKNO,
BUYER_BANKNAME,
BUYER_ZIP,
BUYER_ADD1,
BUYER_ADD2,
BUYER_COMTEL,
BUYER_FAX,
BUYER_MAIL,
BUYER_CHARGER,
BUYER_TELEXT
FROM PROD P INNER JOIN LPROD L ON (P.LPROD_GU = L.LPROD_GU)
            INNER JOIN BUYER B ON (P.BUYER_ID = B.BUYER_ID);

SELECT *
FROM PRODVIEW;

-- SELECT -SCALA 쿼리

-- A001 회원의 기본 정보와 상품 구매건수 조회
SELECT MEM_NAME
,(
    SELECT COUNT(*)
    FROM CART
    WHERE MEM_ID = 'a001'
) CNT
FROM MEMBER
WHERE MEM_ID = 'a001';

WITH BUYERVIEW AS (
SELECT 
             
        BUYER_ID
        , BUYER_NAME
        , BUYER_BANK
        , BUYER_BANKNO
        , BUYER_BANKNAME
        , BUYER_ZIP
        , BUYER_ADD1
        , BUYER_ADD2
        , BUYER_COMTEL
        , BUYER_FAX
        , BUYER_MAIL
        , BUYER_CHARGER
        , BUYER_TELEXT
     
            , LPROD_ID "lprod.lprodId"
            , LPROD_GU "lprod.lprodGu"
            , LPROD_NAME "lprod.lprodName"
        FROM BUYER NATURAL JOIN LPROD
        WHERE BUYER_ID = 'P10101'
    )
    SELECT B.*
        , PROD_ID,PROD_NAME,PROD_COST, PROD_PRICE
    FROM BUYERVIEW B LEFT OUTER JOIN PROD P ON (B.BUYER_ID = P.BUYER_ID);


