spring.application.name=boot-demo6

# 데이터베이스 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# spring.datasource.url=jdbc:oracle:thin:@khc95_high?TNS_ADMIN=/home/ho/Oracle_Cloude_Database/KHC95/Wallet_KHC95
spring.datasource.url=jdbc:oracle:thin:@hr_high?TNS_ADMIN=/home/ho/Oracle_Cloude_Database/HR/Wallet_HR
spring.datasource.username=admin
spring.datasource.password=Tmddusdk4fkdgo!

# HikariCP 설정
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-timeout=20000

# MyBatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.type-aliases-package=kr.or.ddit.dto
mybatis.mapper-locations=classpath:kr/or/ddit/mybatis/mapper/*.xml

server.port=8080

# Logging 설정
spring.output.ansi.enabled=always
logging.include-application-name=false
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(%5p) %clr([%15.15t]){blue} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
logging.exception-conversion-word=%wEx

logging.level.root=INFO
logging.level.kr.or.ddit=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=debug
logging.level.org.springframework.web.servlet.mvc.method.RequestMappingHandlerMapping=DEBUG
logging.level.com.p6spy=info

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# cors 설정
cors.allowed-origins=http://localhost:5174, https://www.naver.com
cors.allowed-methods=GET, POST, PUT, DELETE
cors.allowed-headers=*
cors.allow-credentials=true

jwt.secret-key=aB1cD2eF3gH4iJ5kL6mN7oP8qR9sT0uV
spring.security.oauth2.resourceserver.jwt.authorities-claim-name=roles
spring.security.oauth2.resourceserver.jwt.authority-prefix=