spring.application.name=boot-demo3

# 데이터베이스 설정
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@khc95_high?TNS_ADMIN=/home/ho/Oracle_Cloude_Database/KHC95/Wallet_KHC95
spring.datasource.username=admin
spring.datasource.password=Tmddusdk4fkdgo!

# HikariCP 설정
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=3
spring.datasource.hikari.connection-timeout=20000

# MyBatis 설정
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.jdbc-type-for-null=NULL
mybatis.type-aliases-package=kr.or.ddit.dto
mybatis.mapper-locations=classpath:kr/or/ddit/mapper/*.xml